# Generated by Django 4.2.1 on 2023-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('output_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
